import AboutHC.AboutHC;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Logger;
import javax.swing.Box;
import java.sql.*;
import net.proteanit.sql.DbUtils;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

public class HcForm extends javax.swing.JFrame {
    
    PreparedStatement p_statement = null;
    ResultSet res = null;
    
    public HcForm() {      
        initComponents();
        mainMenu.add(Box.createRigidArea(new Dimension(100,25)));//increase the height from our menu bar       
        patientHospitalizationList();//seeing the results table data
        
        //examinationResults default table ( UI changes )
        JTableHeader newHeader = examinationResults.getTableHeader();
        final Color otherColor = new Color(0, 104, 204); 
        newHeader.setForeground(otherColor); // change the Foreground     
        newHeader.setFont(new Font("Tahome", Font.BOLD, 11)); // font name style size        
    }
    
    PatientInformation newPatientInfo = new PatientInformation();
    HospitalizationForm newHospitalizationForm = new HospitalizationForm();
  
    public void patientHospitalizationList(){
        try {         
            DbConnection dbCon = new DbConnection();
            Connection con = dbCon.getDbConnection();
            
            String queryPatient = "select p.id 'Patiend ID' , p.fname 'First name', p.lname 'Last name',\n" +
                                "h.bed 'Bed Number', h.enter_date 'Enter date', h.exit_date 'Exit date'\n" +
                                "from patients p inner join hospitalization h\n" +
                                "on (p.id = h.patients_id)";
            Statement p_statement = con.prepareStatement(queryPatient);
            ResultSet res;
            res = p_statement.executeQuery(queryPatient);
                 
            patientsVisitsTable.setModel(DbUtils.resultSetToTableModel(res));
            res.close();
        } catch (SQLException ex) {
            
            Logger.getLogger(HcLogin.class.getName()).log(Level.SEVERE, null, ex);  
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBar = new javax.swing.JPanel();
        appointments = new javax.swing.JButton();
        patients = new javax.swing.JButton();
        emr = new javax.swing.JButton();
        mainPatientPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        insuranceForm = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fatherNameField = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        clearSearch = new javax.swing.JButton();
        patientInformation = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        patientFname = new javax.swing.JTextField();
        patientLname = new javax.swing.JTextField();
        displayPatients = new javax.swing.JButton();
        patientID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientsVisitsTable = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        printVisits = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        buttonAddHospitalization = new javax.swing.JButton();
        userLogedIn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Payment = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        examinationResults1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        examinationResults = new javax.swing.JTable();
        btnQueryPatients = new javax.swing.JButton();
        mainMenu = new javax.swing.JMenuBar();
        layoutM = new javax.swing.JMenu();
        checkBoxShowSideBar = new javax.swing.JCheckBoxMenuItem();
        bgColor = new javax.swing.JCheckBoxMenuItem();
        settingsM = new javax.swing.JMenu();
        patientM = new javax.swing.JMenu();
        aboutM3 = new javax.swing.JMenu();
        aboutM2 = new javax.swing.JMenu();
        aboutM = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HC index");
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(1100, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1100, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        appointments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icoAppointments.png"))); // NOI18N
        appointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentsActionPerformed(evt);
            }
        });

        patients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icoPatients.png"))); // NOI18N

        emr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icoEMR.png"))); // NOI18N

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(appointments, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patients, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideBarLayout.createSequentialGroup()
                .addComponent(patients, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emr, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appointments, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
        );

        getContentPane().add(sideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 760));

        mainPatientPanel.setBackground(new java.awt.Color(239, 239, 239));
        mainPatientPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 102, 204));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Patient");
        jLabel2.setOpaque(true);
        mainPatientPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 20));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Patient");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Father's name");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Insurance");

        btnRegister.setText("New Patient");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        clearSearch.setText("Clear Search");
        clearSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSearchActionPerformed(evt);
            }
        });

        patientInformation.setText("Information");
        patientInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientInformationActionPerformed(evt);
            }
        });

        jButton4.setText("Referral");

        patientFname.setText("search patients...");
        patientFname.setToolTipText("Search for a patient");
        patientFname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientFnameMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                patientFnameMousePressed(evt);
            }
        });
        patientFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientFnameActionPerformed(evt);
            }
        });

        displayPatients.setText("...");
        displayPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayPatientsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(clearSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(patientInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(patientID, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(patientFname, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(patientLname, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(displayPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(insuranceForm, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fatherNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayPatients))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insuranceForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fatherNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(clearSearch)
                    .addComponent(patientInformation)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        mainPatientPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 440, 180));

        jLabel10.setBackground(new java.awt.Color(0, 102, 204));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Hospitalization - Beds / Visit");
        jLabel10.setOpaque(true);
        mainPatientPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 150, 20));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        patientsVisitsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        patientsVisitsTable.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(patientsVisitsTable);

        jButton9.setBackground(new java.awt.Color(255, 101, 101));
        jButton9.setText("Delete");

        printVisits.setText("Print");
        printVisits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printVisitsActionPerformed(evt);
            }
        });

        jButton1.setText("New visit");

        buttonAddHospitalization.setText("New hospitalization");
        buttonAddHospitalization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddHospitalizationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAddHospitalization)
                        .addGap(22, 22, 22)
                        .addComponent(printVisits, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(buttonAddHospitalization)
                        .addComponent(printVisits)))
                .addGap(40, 40, 40))
        );

        mainPatientPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 680, 180));

        userLogedIn.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        userLogedIn.setForeground(new java.awt.Color(153, 153, 153));
        userLogedIn.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        userLogedIn.setBorder(null);
        userLogedIn.setEnabled(false);
        userLogedIn.setMargin(new java.awt.Insets(2, 3, 2, 2));
        mainPatientPanel.add(userLogedIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, 120, 20));

        getContentPane().add(mainPatientPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 1160, 210));

        jLabel1.setBackground(new java.awt.Color(0, 102, 204));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Invoice");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 570, 80, 20));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Payment.setText("Payment");

        jButton5.setText("Details");

        jButton6.setText("Collection");

        jButton7.setText("Print");

        jButton10.setText("Cancel");

        jButton11.setBackground(new java.awt.Color(255, 101, 101));
        jButton11.setText("Delete");

        examinationResults1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Invoice code", "Movement", "Date", "Invoice series", "Invoice number", "Printed"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        examinationResults1.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane4.setViewportView(examinationResults1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Payment, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton11)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1136, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Payment)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton10)
                    .addComponent(jButton11)
                    .addComponent(jButton7))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 1160, 160));

        jLabel9.setBackground(new java.awt.Color(0, 102, 204));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Examinations");
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 80, 20));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        examinationResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        examinationResults.setGridColor(new java.awt.Color(204, 204, 204));
        examinationResults.setOpaque(false);
        examinationResults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                examinationResultsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(examinationResults);

        btnQueryPatients.setText("Query Patients");
        btnQueryPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryPatientsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1136, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnQueryPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQueryPatients)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 1160, 330));

        layoutM.setText("Layout");
        layoutM.setMargin(new java.awt.Insets(0, 10, 0, 10));
        layoutM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layoutMActionPerformed(evt);
            }
        });

        checkBoxShowSideBar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        checkBoxShowSideBar.setSelected(true);
        checkBoxShowSideBar.setText("Show Sidebar");
        checkBoxShowSideBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxShowSideBarActionPerformed(evt);
            }
        });
        layoutM.add(checkBoxShowSideBar);

        bgColor.setSelected(true);
        bgColor.setText("Change Interface");
        bgColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgColorActionPerformed(evt);
            }
        });
        layoutM.add(bgColor);

        mainMenu.add(layoutM);

        settingsM.setText("Settings");
        settingsM.setMargin(new java.awt.Insets(0, 10, 0, 10));
        mainMenu.add(settingsM);

        patientM.setText("Patient medical record");
        patientM.setMargin(new java.awt.Insets(0, 10, 0, 10));
        patientM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientMMouseClicked(evt);
            }
        });
        mainMenu.add(patientM);

        aboutM3.setText("Barcode");
        aboutM3.setMargin(new java.awt.Insets(0, 10, 0, 10));
        mainMenu.add(aboutM3);

        aboutM2.setText("Help");
        aboutM2.setMargin(new java.awt.Insets(0, 10, 0, 10));
        mainMenu.add(aboutM2);

        aboutM.setText("About");
        aboutM.setMargin(new java.awt.Insets(0, 10, 0, 10));
        aboutM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMMouseClicked(evt);
            }
        });
        mainMenu.add(aboutM);

        setJMenuBar(mainMenu);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void checkBoxShowSideBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxShowSideBarActionPerformed
        // show or hide sidebar from our HCForm when checkBoxShowSideBar is selected
       if(checkBoxShowSideBar.isSelected()){
           sideBar.setVisible(true);//show
       }else{
           sideBar.setVisible(false);//hide
       }
    }//GEN-LAST:event_checkBoxShowSideBarActionPerformed

    private void patientIDasdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientIDasdActionPerformed
         
    }//GEN-LAST:event_patientIDasdActionPerformed

    private void patientMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientMMouseClicked
        // TODO add your handling code here:
        PrintForm showPrintForm = new PrintForm();
        showPrintForm.setVisible(true);
    }//GEN-LAST:event_patientMMouseClicked
    
    private void printVisitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printVisitsActionPerformed
        //**print report for patients hospitalizations-beds
        String date = new SimpleDateFormat("dd-MM-yyyy").format(new Date());
        MessageFormat headerMessage = new MessageFormat("HospitalCare - Hospitalization Report_: " + date.toString()); //**set header message
        MessageFormat footerMessage = new MessageFormat("-------------End of the report-------------");//**set footer message
        
        try {
            patientsVisitsTable.print(JTable.PrintMode.NORMAL.FIT_WIDTH,headerMessage , footerMessage);
        } catch (PrinterException ex) {
            Logger.getLogger(HcForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printVisitsActionPerformed

    private void appointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentsActionPerformed
        // TODO add your handling code here:
        HCAppointments AppointNew = new HCAppointments();
        AppointNew.setVisible(true);
    }//GEN-LAST:event_appointmentsActionPerformed

    private void bgColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgColorActionPerformed
        //**Change the panel's background color
        if(bgColor.isSelected()){       
            mainPatientPanel.setBackground(new Color(0, 0, 94, 0));
        }else{
            mainPatientPanel.setBackground(Color.lightGray);
        }
    }//GEN-LAST:event_bgColorActionPerformed

    private void layoutMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layoutMActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_layoutMActionPerformed

    private void aboutMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMMouseClicked
        //**Call the AboutHC class and show it when 'About' is clicked
        AboutHC abShow = new AboutHC();
        abShow.setVisible(true);
    }//GEN-LAST:event_aboutMMouseClicked
    
    private void examinationResultsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_examinationResultsMouseClicked
  
       //newPatientInfo.patientFname1.setText(patientFname.getText());
    }//GEN-LAST:event_examinationResultsMouseClicked

    private void patientIDasdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientIDasdMouseClicked
        // TODO add your handling code here:
        patientID.setText(null);
    }//GEN-LAST:event_patientIDasdMouseClicked

    private void asd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asd
        // TODO add your handling code here:
    }//GEN-LAST:event_asd

    private void patientIDasdMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientIDasdMouseReleased
        // TODO add your handling code here:
        patientID.setText(null);
    }//GEN-LAST:event_patientIDasdMouseReleased

    private void btnQueryPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryPatientsActionPerformed
        try {
            DbConnection dbCon = new DbConnection();
            Connection con = dbCon.getDbConnection();

            String sql = "SELECT  p.id 'Patient ID', p.fname 'First name', p.lname 'Last name',p.address,p.father_name,p.phone,p.dob,p.insurance,p.patients_info FROM patients p";
                               
            p_statement = con.prepareStatement(sql);
            res = p_statement.executeQuery(sql);

            examinationResults.setRowHeight(30);//**set row height
            examinationResults.setModel(DbUtils.resultSetToTableModel(res));
        } 
        catch (SQLException ex) {
            Logger.getLogger(HcForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{     
            try {
                res.close();             
            } 
            catch (SQLException ex) {
                Logger.getLogger(HcForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnQueryPatientsActionPerformed

    private void displayPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayPatientsActionPerformed
        //**----ArrayList - patients ----//
        //PatientSearchShow.getPatients() method;
        JTable table = new JTable(); // create new Jtable
        DefaultTableModel defaultModel = new DefaultTableModel();//new default table model

        Object[] columnsName = new Object[5];//generate column names
        columnsName[0] = "ID";// column name ID
        columnsName[1] = "First Name";
        columnsName[2] = "Last Name";
        columnsName[3] = "Address";
        columnsName[4] = "Father's Name";

        defaultModel.setColumnIdentifiers(columnsName);//add the column names

        Object[] rowData = new Object[5];
        for(int i = 0; i < PatientSearchShow.getPatients().size(); i++){
            rowData[0] = PatientSearchShow.getPatients().get(i).getId();
            rowData[1] = PatientSearchShow.getPatients().get(i).getFname();
            rowData[2] = PatientSearchShow.getPatients().get(i).getLname();
            rowData[3] = PatientSearchShow.getPatients().get(i).getAddress();
            rowData[4] = PatientSearchShow.getPatients().get(i).getFatherName();
            //rowData[3] = getUsers().get(i).getAge();
            defaultModel.addRow(rowData);
        }
        table.setModel(defaultModel);

        PatientSearchShow window = new PatientSearchShow();
        JPanel panel = new JPanel();
        panel.setLayout(new BorderLayout());
        JScrollPane pane = new JScrollPane(table);
        panel.add(pane,BorderLayout.CENTER);
        window.setContentPane(panel);
    }//GEN-LAST:event_displayPatientsActionPerformed

    private void patientFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientFnameActionPerformed
           try {
            DbConnection dbCon = new DbConnection();
            Connection con = dbCon.getDbConnection();
         
            //##creating our sql query,( making a selection from the patients enitity and inner join the examinations enitity .
            //##fetch sql data from examinations,and patients ->current collumns are : "Patient ID", "First name", "Last name", "MRI", "CT", "CR".... 
            String sql = "select  p.id 'Patient ID', p.fname 'First name', p.lname 'Last name',p.address,p.father_name,p.postcode,p.phone,p.email,p.dob,p.insurance,p.nationality,p.patients_info, e.MRI, e.CT, e.CR, e.date_time_examination\n" +
                        "from patients p inner join examinations e\n" +
                        "on (p.id = e.patients_id) where fname like '%" + patientFname.getText() + "%'"; //**search for a patient, when the user inputs a patient's name
                               
            p_statement = con.prepareStatement(sql);
            res = p_statement.executeQuery(sql);

            if(res.next()){
                int showPatientId = res.getInt("Patient ID");
                String intToString = Integer.toString(showPatientId);
                newHospitalizationForm.hospitalizationPatientId.setText(intToString);//hospitalization form
                patientID.setText(intToString);

                fatherNameField.setText(res.getString("father_name"));
                
                String showFirstName = res.getString("First name");
                newPatientInfo.informationFname.setText(showFirstName);
                newHospitalizationForm.hospitalizationPatientFname.setText(showFirstName);//hospitalization form
                patientFname.setText(showFirstName);
                
                String showLastName = res.getString("Last name");
                newPatientInfo.informationLname.setText(showLastName);
                newHospitalizationForm.hospitalizationPatientLname.setText(showLastName);//hospitalization form
                patientLname.setText(showLastName);
                
                String showFatherName = res.getString("p.father_name");
                
                //passing the data into the PatientInformation class 
                newPatientInfo.informationGetPatientID.setText(intToString);
                newPatientInfo.informationAddress.setText(res.getString("p.address"));
                newPatientInfo.informationDob.setDate(res.getDate("p.dob"));
                newPatientInfo.informationEmail.setText(res.getString("p.email"));
                newPatientInfo.informationFatherName.setText(res.getString("p.father_name"));
                newPatientInfo.informationPostCode.setText(res.getString("p.postcode"));
                newPatientInfo.informationTelNumber.setText(res.getString("p.phone"));
                newPatientInfo.informationInsurance.setText(res.getString("p.insurance"));
                insuranceForm.setText(res.getString("p.insurance"));
                newPatientInfo.informationNationality.setText(res.getString("p.nationality"));
                newPatientInfo.informationInfo.setText(res.getString("p.patients_info"));
       
                newPatientInfo.displaySelectedPatient.setText("Patient name: " + showFirstName + " ," + showLastName + "  | " +" Father's name : " + showFatherName);
            }       
                examinationResults.setRowHeight(30);//**set row height
                examinationResults.setModel(DbUtils.resultSetToTableModel(res));                
        } catch (SQLException ex) {
            Logger.getLogger(HcForm.class.getName()).log(Level.SEVERE, null, ex);
        }finally{     
            try {
                res.close();             
            } catch (SQLException ex) {
                Logger.getLogger(HcForm.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }
    }//GEN-LAST:event_patientFnameActionPerformed

    private void patientInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientInformationActionPerformed
        // TODO add your handling code here:
        newPatientInfo.setVisible(true);
    }//GEN-LAST:event_patientInformationActionPerformed

    private void clearSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearSearchActionPerformed
        //** When the 'Clear' button is clicked , set our fields to null
        patientID.setText(null);
        patientFname.setText(null);
        patientLname.setText(null);
        fatherNameField.setText(null);

        //clear Patient information fields
        newPatientInfo.displaySelectedPatient.setText("*No patient selected..");
        newPatientInfo.informationGetPatientID.setText("*No patient id found..");
        newPatientInfo.informationFname.setText(null);
        newPatientInfo.informationLname.setText(null);
        newPatientInfo.informationAddress.setText(null);
        newPatientInfo.informationDob.setDate(null);
        newPatientInfo.informationEmail.setText(null);
        newPatientInfo.informationFatherName.setText(null);
        newPatientInfo.informationInsurance.setText(null);
        newPatientInfo.informationNationality.setText(null);
        newPatientInfo.informationPostCode.setText(null);
        newPatientInfo.informationTelNumber.setText(null);
        newPatientInfo.informationInfo.setText(null);          
    }//GEN-LAST:event_clearSearchActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        //** Creating our Registration patients form, to register new patients, when 'New patient' button is clicked
        RegistrationNewPatient RegistrationNew = new RegistrationNewPatient();
        RegistrationNew.setVisible(true);    
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void patientFnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientFnameMouseClicked
        // TODO add your handling code here:
        patientFname.setText(null);
    }//GEN-LAST:event_patientFnameMouseClicked

    private void patientFnameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientFnameMousePressed
        // TODO add your handling code here:
        patientFname.setText(null);
    }//GEN-LAST:event_patientFnameMousePressed

    private void buttonAddHospitalizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddHospitalizationActionPerformed
        // TODO add your handling code here:
       
        newHospitalizationForm.setVisible(true);
    }//GEN-LAST:event_buttonAddHospitalizationActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new HcForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Payment;
    private javax.swing.JMenu aboutM;
    private javax.swing.JMenu aboutM2;
    private javax.swing.JMenu aboutM3;
    private javax.swing.JButton appointments;
    private javax.swing.JCheckBoxMenuItem bgColor;
    private javax.swing.JButton btnQueryPatients;
    public javax.swing.JButton btnRegister;
    private javax.swing.JButton buttonAddHospitalization;
    private javax.swing.JCheckBoxMenuItem checkBoxShowSideBar;
    private javax.swing.JButton clearSearch;
    private javax.swing.JButton displayPatients;
    private javax.swing.JButton emr;
    public javax.swing.JTable examinationResults;
    private javax.swing.JTable examinationResults1;
    private javax.swing.JTextField fatherNameField;
    private javax.swing.JTextField insuranceForm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JMenu layoutM;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JPanel mainPatientPanel;
    public javax.swing.JTextField patientFname;
    public javax.swing.JTextField patientID;
    public javax.swing.JButton patientInformation;
    public javax.swing.JTextField patientLname;
    private javax.swing.JMenu patientM;
    private javax.swing.JButton patients;
    private javax.swing.JTable patientsVisitsTable;
    private javax.swing.JButton printVisits;
    private javax.swing.JMenu settingsM;
    private javax.swing.JPanel sideBar;
    public javax.swing.JTextField userLogedIn;
    // End of variables declaration//GEN-END:variables
    
}
